name: Test

on:
  push:
      branches:
        - dev
        - main
  page_build:
  release:
    types:
      - created

jobs:
  hello-world:
      runs-on: ubuntu-20.04
      name: hello-world
      steps:
      - id: Say_hello_world
        run: "echo Welcome to the Github Actions workshop !"

  unit-test:
      runs-on: ubuntu-20.04
      name: unit-test
      steps:
      - id: Checkout_repo
        run: "echo Checkout_repo"
      - id: Unit-tests
        run: "make tests_run"
      - id: Coverage
        run: "make tests_cover"