name: Tests

on:
  push:
      branches:
        - dev
        - main
  page_build:
  release:
    types:
      - created

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    name: hello-world
    steps:
    - id: Say_hello_world
      run: "echo hello world"

  unit-test:
    runs-on: ubuntu-20.04
    name: unit-test
    container: epitechcontent/epitest-docker
    steps:
    - run: "mkdir -p artifact/"
    - run: echo hello > artifact/unit_test.txt
    - uses: actions/checkout@v1
    - id: Unit-tests
      run: "make tests_run > artifact/unit_test.txt"
    - id: Coverage
      run: "make coverage > artifact/coverage.txt"
    - uses: actions/upload-artifact@v2
      with:
        name: coverage_outputs
        path: artifact/coverage.txt