name: Test

on:
  push:
      branches:
        - dev
        - main
  page_build:
  release:
    types:
      - created

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    name: hello-world
    steps:
    - id: Say_hello_world
      run: "echo hello word"

  unit-test:
    runs-on: ubuntu-20.04
    name: unit-test
    container: epitechcontent/epitest-dockere
    steps:
    - uses: actions/checkout@v1
    - id: Unit-tests
      run: "make tests_run"
    - id: Coverage
      run: "make coverage"